name: Go - Run tests and benchmark

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      path:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'The path of the folder where the _test.go file is'
        # Default value if no value is explicitly provided
        default: 'answer_list/week48/4821-cr/'
        # Input has to be provided for the workflow to run
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Test and Benchmark
      run: go test -v -benchmem -bench=. -cover
      working-directory: ${{ github.event.inputs.path }}
